# Generated by Django 4.2.3 on 2023-07-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="foto_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
